

import Link from "next/link";

export default function TermsOfOffensePage() {
  return (
    <main className="min-h-screen  text-[#E7E9EA] font-sans flex flex-col items-center justify-center px-4 py-10 sm:py-20">
      <div className="max-w-3xl w-full bg-[#16181C] rounded-2xl shadow-xl p-6 sm:p-10 border border-[#222]">
        <h1 className="text-3xl sm:text-4xl font-bold text-[#1D9BF0] text-center mb-6">
          Terms of Offense
        </h1>
        <p className="mb-6 text-center text-[#999] italic">
          Because normal terms were too boring for us.
        </p>

        <div className="space-y-6 text-sm sm:text-base leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">1. Zero Responsibility Policy</h2>
            <p>
              By using XcusesHub, you agree that we take zero responsibility for any roast-related meltdowns,
              identity crises, or existential dread that may result from our brutally honest AI judge.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">2. Roast-At-Your-Own-Risk</h2>
            <p>
              If you upload your résumé, GitHub, or any trace of your developer existence, you're basically
              begging us to roast you. Don't say we didn’t warn you (we just did).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">3. No Feelings Were Harmed… Allegedly</h2>
            <p>
              All offensive content is automatically generated by an AI that was trained on the internet.
              So if you're offended, please redirect your emotions to <code>/dev/null</code>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">4. We’re Not Hiring</h2>
            <p>
              XcusesHub is a joke. If you thought this was a serious hiring platform, we genuinely admire your optimism.
              Please lower your expectations immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">5. By Reading This, You're Legally Doomed</h2>
            <p>
              Just kidding. But seriously, if you've read this far, you're probably already too deep into our
              sarcastic void. Welcome to the club.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">6. Updates, Probably Never</h2>
            <p>
              These Terms of Offense may or may not be updated. If they are, we won’t notify you.
              If they’re not, well, you weren’t checking anyway.
            </p>
          </section>
        </div>

        <div className="mt-10 text-center">
          <Link
            href="/"
            className="inline-block px-6 py-2 rounded-full bg-[#1D9BF0] text-black font-semibold hover:bg-[#0a7acb] transition-colors text-sm sm:text-base"
          >
            Escape While You Can
          </Link>
        </div>
      </div>
    </main>
  );
}
